# TODO

# PISA

## Model running and processing of the data

```{r}
model_fitted_p <- '
  gen_dse =~ search_info + evaluate_info + 
  explain_content + share_content + pair_collab + 
  write_text
  spec_dse =~ programming + identify_error + logical_solution
  '
  
fitgroup_p <- cfa(model = model_fitted_p, 
                data = pisa, 
                group = "CNT",
                ordered = TRUE,
                estimator = "DWLS"
              )
```

```{r}
# Obtenemos todos los parámetros

all_params_p <- parameterEstimates(fitgroup_p, standardized = TRUE)

# Operador =~

factor_loadings_all_groups_p <- all_params_p %>%
  filter(op == "=~")

# Extraemos las labels

group_labels_p <- lavInspect(fitgroup_p, "group.label")

# Dataframe con todos los países

country_map_p <- data.frame(group = 1:length(group_labels_p), CNT = unlist(group_labels_p))

# Dataframe con ambas dimensiones

factor_loadings_all_groups_p <- factor_loadings_all_groups_p %>%
  left_join(country_map_p, by = "group")

# Dataframe gen dse

loadings_gen_dse_p <- factor_loadings_all_groups_p %>%
  filter(lhs == "gen_dse") %>%
  select(CNT, item = rhs, loading = std.all, latent_factor = lhs)

# Etiquetas tres países con peor ajuste

labels_gen_dse_p <- loadings_gen_dse_p %>%
  group_by(item) %>%
  slice_min(order_by = loading, n = 3) %>%
  ungroup()

# Dataframe spec dse

loadings_spec_dse_p <- factor_loadings_all_groups_p %>%
  filter(lhs == "spec_dse") %>%
  select(CNT, item = rhs, loading = std.all, latent_factor = lhs)

# Etiquetas tres países con menor ajuste

labels_spec_dse_p <- loadings_spec_dse_p %>%
  group_by(item) %>%
  slice_min(order_by = loading, n = 3) %>%
  ungroup()

```

## General DSE loadings graph

```{r}
# Gráfico cleaveland autoeficacia general

library(forcats)

plot_gen_dse_p <- ggplot(loadings_gen_dse_p,
                       aes(x = loading,
                           y = fct_reorder(item, loading, .fun = median, .desc = FALSE))) +
  geom_point(aes(color = '#B42012'), size = 3, alpha = 0.7) + 
    geom_text(data = labels_gen_dse_p, 
            aes(label = CNT), 
            nudge_y = 0.3,
            size = 2.5,
            color = "black",
            check_overlap = TRUE) +
  scale_color_identity(name = "Factor", 
                       guide = "legend", 
                       labels = c("General")) +
  labs(title = "Cargas Factoriales: Autoeficacia General",
       x = "Carga Factorial Estandarizada",
       y = "Ítem") +
  theme_minimal(base_size = 10) +
  theme(axis.text.y = element_text(size = 8),
        plot.title = element_text(hjust = 0.5),
        legend.position = "top")

plot_gen_dse_p

# Cleaveland autoeficacia especializada
# Fijar el gráfico a x = .3

```

## Specialized DSE loadings graph

```{r}
plot_spec_dse_p <- ggplot(loadings_spec_dse_p,
                        aes(x = loading,
                            y = fct_reorder(item, loading, .fun = median, .desc = FALSE))) +
  geom_point(aes(color = '#E16462'), size = 3, alpha = 0.7) +
    geom_text_repel(data = labels_spec_dse_p, 
                  aes(label = CNT), 
                  size = 2.5,
                  color = "black",
                  box.padding = 0.4,
                  point.padding = 0.2,
                  min.segment.length = 0,
                  max.overlaps = Inf) +
  scale_color_identity(name = "Factor", 
                       guide = "legend", 
                       labels = c("Especializada")) +
  labs(title = "Cargas Factoriales: Autoeficacia Especializada", 
       x = "Carga Factorial Estandarizada",
       y = "Ítem") +
  theme_minimal(base_size = 10) +
  theme(axis.text.y = element_text(size = 8),
        plot.title = element_text(hjust = 0.5),
        legend.position = "top")

plot_spec_dse_p
```

# ICILS

## Model running and processing of the data
```{r}
model_fitted_i <- '
  gen_dse =~ search_info + evaluate_info + install_app +
              share_content +
              create_media + insert_image + edit_image + change_settings
  spec_dse =~ programming + visual_coding + develop_webpage
  '

fitgroup_i <- cfa(model = model_fitted_i, 
              data = icils,
              estimator = "DWLS",
              ordered = T)

```

```{r}
# Obtenemos todos los parámetros

all_params_i <- parameterEstimates(fitgroup_I, standardized = TRUE)

# Operador =~

factor_loadings_all_groups_i <- all_params_i %>%
  filter(op == "=~")

# Extraemos las labels

group_labels_i <- lavInspect(fitgroup_i, "group.label")

# Dataframe con todos los países

country_map_i <- data.frame(group = 1:length(group_labels_i), CNT = unlist(group_labels_i))

# Dataframe con ambas dimensiones

factor_loadings_all_groups_i <- factor_loadings_all_groups_i %>%
  left_join(country_map_i, by = "group")

# Dataframe gen dse

loadings_gen_dse_i <- factor_loadings_all_groups_i %>%
  filter(lhs == "gen_dse") %>%
  select(CNT, item = rhs, loading = std.all, latent_factor = lhs)

# Etiquetas tres países con peor ajuste

labels_gen_dse_i <- loadings_gen_dse_i %>%
  group_by(item) %>%
  slice_min(order_by = loading, n = 3) %>%
  ungroup()

# Dataframe spec dse

loadings_spec_dse_i <- factor_loadings_all_groups_i %>%
  filter(lhs == "spec_dse") %>%
  select(CNT, item = rhs, loading = std.all, latent_factor = lhs)

# Etiquetas tres países con menor ajuste

labels_spec_dse_i <- loadings_spec_dse_i %>%
  group_by(item) %>%
  slice_min(order_by = loading, n = 3) %>%
  ungroup()

```

## General DSE loadings graph
```{r}
# Gráfico cleaveland autoeficacia general

library(forcats)

plot_gen_dse_i <- ggplot(loadings_gen_dse_i,
                       aes(x = loading,
                           y = fct_reorder(item, loading, .fun = median, .desc = FALSE))) +
  geom_point(aes(color = '#B42012'), size = 3, alpha = 0.7) + 
    geom_text(data = labels_gen_dse_i, 
            aes(label = CNT), 
            nudge_y = 0.3,
            size = 2.5,
            color = "black",
            check_overlap = TRUE) +
  scale_color_identity(name = "Factor", 
                       guide = "legend", 
                       labels = c("General")) +
  labs(title = "Cargas Factoriales: Autoeficacia General",
       x = "Carga Factorial Estandarizada",
       y = "Ítem") +
  theme_minimal(base_size = 10) +
  theme(axis.text.y = element_text(size = 8),
        plot.title = element_text(hjust = 0.5),
        legend.position = "top")

plot_gen_dse_i

# Cleaveland autoeficacia especializada
# Fijar el gráfico a x = .3

```

## Specialized DSE loadings graph
```{r}
plot_spec_dse_i <- ggplot(loadings_spec_dse_i,
                        aes(x = loading,
                            y = fct_reorder(item, loading, .fun = median, .desc = FALSE))) +
  geom_point(aes(color = '#E16462'), size = 3, alpha = 0.7) +
    geom_text_repel(data = labels_spec_dse_i, 
                  aes(label = CNT), 
                  size = 2.5,
                  color = "black",
                  box.padding = 0.4,
                  point.padding = 0.2,
                  min.segment.length = 0,
                  max.overlaps = Inf) +
  scale_color_identity(name = "Factor", 
                       guide = "legend", 
                       labels = c("Especializada")) +
  labs(title = "Cargas Factoriales: Autoeficacia Especializada", 
       x = "Carga Factorial Estandarizada",
       y = "Ítem") +
  theme_minimal(base_size = 10) +
  theme(axis.text.y = element_text(size = 8),
        plot.title = element_text(hjust = 0.5),
        legend.position = "top")

plot_spec_dse_i
```

