---
editor: visual
---

# Self-efficacy and Digital Technologies

Originally formulated by @bandura_selfefficacy_1982, self-efficacy is defined as "judgments of how well one can execute courses of action required to deal with prospective situations." (p. 122). This construct is fundamental to human agency, as it help to understand how individuals approach challenges, persist despite setbacks, and develop competence in complex domains. It does so by facilitating the establishment of standards and the attainment of performance accomplishments across learning activities [@bandura_selfefficacy_1995; @steele_stereotype_1995;@bandura_selfefficacy_1997]. Self-efficacy has proven to be particularly relevant for achieve learning with digital technologies [@chen_ictrelated_2020; @hatlevik_digital_2015; @aesaert_accuracy_2017]. A whole thematic research agenda has opened up around self-efficacy role on the adoption of new technologies and the develop of competences on digital environments, although there are scattered efforts when it comes to measuring this construct. 

Early proposals aims on measuring self-efficacy in general computer domains and specific software application tasks [@compeau_computer_1995;@durndell_computer_2002; @weigel_technical_2014], while other studies focuses more on the online browsing and communication [@eastin_internet_2000a; @hsu_internet_2004]. In view of the growing hybridization between computational components and the use of the network for social interaction, the discussion on self-efficacy have centered on the ICT framework, which consider a group of generalized tasks as digital information processing, communication and content creation [@aesaert_exploring_2014; @hatlevik_students_2018] but also more computational skills, such as programming or web development [@rohatgi_role_2016]. 

During the second decade of the 21st century, amidst the internet massification, a broad consensus emerged around the idea that ICT self-efficacy was better understood when distinguishing the different areas of use of technologies [@liang_internet_2008; @papastergiou_enhancing_2010; @aesaert_exploring_2014]. Studies adopting this framework consistently identified contrasting associations with key variables related to competence development: while self-efficacy in areas such as data management, communication, and content creation tended to align positively with broader digital proficiency, self-efficacy in more advanced domains—such as web development and programming—often showed different or even inverse patterns of relationship [@rohatgi_role_2016; @gebhardt_gender_2019].

@ulfert-blank_assessing_2022 pushed the boundaries of the traditional ICT self-efficacy framework by highlighting its limited capacity to keep pace with the rapidly evolving nature of digital systems. Due to the accelerated rate of technological change, many ICT self-efficacy items quickly became obsolete as the applications, functions, or devices they referenced fell out of use. In response to this problem, @ulfert-blank_assessing_2022 proposed the development of new constructs labelled as Digital Self-efficacy (DSE), defined as the individual’s confidence to successfully organize and execute the necessary actions to perform specific tasks related to the use of technologies in independent and different contexts. @ulfert-blank_assessing_2022 ground its theoretical contribution on the recent guidelines of the European Framework of Digital Competence Development (DigComp) [@europeancommissionjointresearchcentre_digcomp_2022], emphasizing that constructs related to digital engagement must encompass a wide range of functions and tasks across entire digital systems in order to remain coherent over time and across diverse technological ecologies.

The problem is that the bidimensional aproach to self-efficacy is no longer suitable with recent definitions of Digital competence. New critical competences beyond the informational, communicative, and creative dimensions have begun to be incorporated, specifically safety (i.e., the ability to protect personal data and digital well-being while navigating online environments) and problem-solving (i.e., the capacity to diagnose and resolve technical issues and strategically select appropriate technological solutions). With the introduction of these new types of activity, the DigComp framework tends to favor a multidimensional perspective that organises digital tasks by competence areas rather than by general or specialized use associated with each task [@ulfert-blank_assessing_2022].

Considering the disagreement regarding the dimensionality of digital self-efficacy, it is necessary to study how this conceptual discussion has been adressed by large-scale measurements, as well as the different understandings of self-efficacy that each of them has.

# ICILS and the bi-dimensional DSE

The International Computer and Information Literacy Study (ICILS), conducted by the International Association for the Evaluation of Educational Achievement (IEA), stands as the primary large-scale assessment to explicitly adopt and maintain a bidimensional approach to ICT self-efficacy. ICILS aims to measure students' Computer and Information Literacy (CIL) through standardized performance tests while simultaneously examining the influence of social background variables on digital proficiency. The study has been conducted three times —2013, 2018, and 2023—, involving large representative samples of 8th-grade students across various educational systems.

Conceptually, ICILS draws upon elements of @bandura_perceived_1993 view of self-efficacy to propose a measurement of how students judge their capabilities to execute courses of action using Information and Communication Technologies [@fraillon_iea_2025a]. The study since its inception distinguishes between self-efficacy in general ICT tasks, which reflects confidence in performing everyday activities such as information retrieval, online communication and content creation, and self-efficacy in specialized ICT tasks, which targets more complex computational operations like programming or database management [@fraillon_iea_2025a]. By operationalizing these constructs separately, ICILS acknowledges that confidence in routine digital interactions functions as a distinct factor from the high-level technical creation.

While the bidimensional structure has remained stable, the specific composition of the batteries has evolved across cycles to mirror the changing digital landscape. Between 2013 and 2018, the terminology shifted from “basic” and “advanced” to “general” and “specialized”, accompanied by a recalibration of items: the general dimension expanded to include tasks like software installation, while the specialized dimension shrank, discarding tasks such as virus removal. The 2023 cycle introduced more profound modifications. The specialized dimension was further narrowed to focus almost exclusively on visual coding, text-based programming and web creation, moving away from earlier items related to local networks or database management. The general dimension was updated to incorporate critical information literacy tasks, such as finding original sources or changing device settings. Furthermore, item stems were rephrased to remove explicit references to "computers," acknowledging the diversity of modern devices.

The bidimensional structure of ICT self-efficacy in ICILS has been supported by robust psychometric validation across all three ICILS cycles, although the specific analytical strategies have evolved to reflect advancements in large-scale assessment methodology. In the 2013 and 2018 cycles, the validation process followed a rigorous sequential approach: Exploratory Factor Analysis (EFA) was first employed during field trials to determine the dimensionality of the item pools, and this structure was subsequently confirmed using Confirmatory Factor Analysis (CFA) within a Structural Equation Modeling (SEM) framework [@fraillon_icils_2015]. The 2018 cycle further expanded this validation by incorporating Multi-group CFA (MGCFA), allowing for a precise assessment of measurement invariance to ensure that the general and specialized constructs were comparable across diverse educational systems [@fraillon_iea_2020]. In the most recent 2023 cycle, the assessment shifted away from the SEM framework, adopting Principal Component Analysis (PCA) to verify dimensionality and transitioning to a pure Item Response Theory (IRT) approach. Specifically, the study employed Partial Credit Models (PCM) and Multi-group PCM to establish scale validity and cross-national comparability through fit indices such as RMSD and WRMSD [@fraillon_iea_2025]. Collectively, these rigorous analyses consistently justify the decision to operationalize digital self-efficacy as two distinct, albeit related, constructs.

The empirical distinctiveness of the bidimensional framework is reinforced by the diverging relationships that general and specialized self-efficacy exhibit with digital competence and gender across diverse educational systems. Consistent analyses from ICILS international reports and various independent studies demonstrate that self-efficacy in general ICT tasks functions as a robust, positive predictor of CIL achievement [@rohatgi_role_2016; @aydin_multilevel_2022; @fraillon_preparing_2020; @fraillon_international_2025] and a consistent mediator between other relevant student background variables and test performance [@campos_digital_2024; @mirazchiyski_students_2025]. Conversely, self-efficacy in specialized tasks has repeatedly shown a null or even negative association with CIL performance. This discrepancy is often attributed to a "misalignment" between the high-level technical skills that specialized ICT self-efficacy encompasses (e.g., programming) and the information-management focus of CIL assessments, where technical expertise does not necessarily translate into informational competence [@rohatgi_role_2016; @fraillon_iea_2019]. Furthermore, this distinction unveils critical gender dynamics: while boys consistently report higher specialized self-efficacy, this gap disappears in the general dimension [@gebhardt_gender_2019], even though girls outperform them in CIL scores across almost all educational systems [@kennedy_relationships_2025].

# The unidimensional DSE approach on PISA

The Programme for International Student Assessment (PISA) is a recognized cross-country study that is developed by the OECD. The primary objective of PISA is to assess the abilities of 15-year-old adolescents to apply their knowledge in reading, mathematics, and science to address challenges in real-life situations [@oecd_what_2023]. The first version of this study was published in 2000, and its eighth and latest published cycle was conducted in 2022. 

The most recent versions of PISA has begun to include a technology assessment framework that considers ICT use, access and digital competences of students [@oecd_pisa_2023]. In PISA, digital self-efficacy is used as a proxy for digital competences, as the study does not have a practical test to measure achievement on technological tasks like ICILS. PISA uses the framework provided by the European Commission's to adress the levels of proficiency of students on five areas of digital competence: information, communication, creation, safety, and problem solving [@europeancommissionjointresearchcentre_digcomp_2022]. As a result of adopting the most recent theoretical developments on digital competence, PISA presents updates on DSE measurement, adding tasks not considered in ICILS, such as protecting data privacy or representing a computational solution as an algorithm.

Several similarities between PISA and ICILS measures of DSE can be found on @tbl-comparison. Firstly, the items are similar in scope, as both studies consider information, communication and digital content creation, including simple tasks such as evaluating online information or upload multimedia and advanced tasks as programming and web development. Second, the items in both studies have similar wording. But in contrast to ICILS, PISA has operationalized students’ ability to carry out technological tasks as a unidimensional construct across the cycles, treating the heterogeneity of tasks as reflective of variation along a single latent continuum rather than of distinct underlying dimensions [@oecd_pisa_2018_framework; @oecd_pisa_2023].

Psychometric validation in PISA has consistently relied on Item Response Theory (IRT) scaling, most commonly using Partial Credit Models, preceded by exploratory analyses of dimensionality (e.g., principal component analyses) to justify the assumption of unidimensionality [@oecd_pisa_2024]. Scale quality has been evaluated through item-fit statistics, category functioning, reliability indicators, and multi-group IRT models to ensure cross-national comparability [@oecd_pisa_2024; @adams_wu_wilson_2012_conquest]. However, unlike ICILS, PISA has not systematically tested an alternative multidimensional measurement models for DSE, nor has it examined whether task types comparable to ICILS’ “general” and “specialized” domains form empirically distinguishable latent factors. As a result, while the PISA self-efficacy battery exhibits theoretical advances with a strong psychometric properties under a unidimensional specification, the question of whether students’ digital self-efficacy is more accurately represented by a bidimensional structure remains empirically open and warrants explicit testing.

```{r}
#| label: tbl-comparison
#| tbl-cap: "DSE item comparison between PISA and ICILS."

library(kableExtra)
library(openxlsx)

table <- openxlsx::read.xlsx(here::here("input", "documents", "batteries_icils_pisa_selfeff_comparison.xlsx"), fillMergedCells = TRUE)
table[is.na(table)] <- ""

table |>
  dplyr::select(Competence.area,Competence,Common.label,ICILS.Label,PISA.Label,Type.of.DSE)|>
  knitr::kable() |>
scroll_box(height="800px")

#Hay que añadir la cantidad de NA por item en esta tabla
```

The unidimensional operationalization of digital self-efficacy in PISA has substantive analytical consequences on how empirical relationships are identified and interpreted. Studies that explicitly model the PISA ICT self-efficacy battery as a single latent construct consistently report significant associations with gender, socioeconomic status, ICT use, motivational orientations toward technology, and academic achievement across reading, mathematics, and science [@chen_ictrelated_2020; @yu_ict_2022; @hori_impact_2021; @kunina-habenicht_ict_2020]. These findings suggest that digital self-efficacy, as measured in PISA, functions as a meaningful predictor of educational outcomes [@yu_ict_2022]. However, by collapsing heterogeneous digital tasks into a single continuum, this specification implicitly assumes functional equivalence between different forms of digital engagement, from general information-related activities to more complex forms of digital problem-solving and content production [@oecd_pisa_2023].

Evidence from PISA-based studies that introduce bidimensional distinctions suggests that such heterogeneity matters: while self-efficacy related to general or information-oriented digital skills tends to show robust positive associations with achievement and background variables, self-efficacy related to more specialized or computational domains often displays weaker, null, or qualitatively different relationships [@tomte_genderdifferences_2011; @hristov_understanding_2026]. Yet, despite these recurrent patterns, these dimensional splits have rarely been subjected to formal tests of construct validity or cross-national measurement invariance, leaving open the question of whether a bidimensional specification —systematically validated as in ICILS— would yield substantively different and more precise insights into digital inequality and competence formation within the PISA framework [@fraillon_iea_2025a].

# Country level and Gender

When comparing psychological or educational constructs across social groups or countries, the issue of measurement invariance becomes an indispensable methodological requirement. As recent scholarship shows, social science research often assumes that instruments capture the same underlying meaning across culturally or structurally diverse populations, even though socialization trajectories, interpretive repertoires, and institutional conditions can substantially alter how individuals understand and respond to items [@davidov_measurement_2014;@leitgob_measurement_2023]. 

The contrast between the dimensionality of DSE on both studies is not a matter of chance when it comes to evaluating the socio-cultural context in which they are embedded. Available evidence suggests that the magnitude and direction of DSE vary significantly between countries, indicating that self-efficacy is not expressed uniformly but is mediated by social expectations [@gebauer_crosscultural_2021], and differential degrees of exposure to technologies [@hatlevik_students_2018; @senkbeil_ictrelated_2022]. Education systems may associate divergent meanings with seemingly similar tasks with technologies, whether due to contrasting curricular trajectories [@martin-parraga_selfperception_2023; @annemann_teachers_2025], heterogeneity in access to digital infrastructure or differences in the social valuation of certain technological skills [@annemann_teachers_2025; @conte_unlocking_2025].

The different understandings of the DSE items can be expressed between-countries, so cannot be assumed without first examining the metric equivalence of the construct in both studies. Relevant research has accepted the international validity of the ICILS two-dimensionality proposal [@campos_digital_2024; @gebhardt_gender_2019; @karpinski_noncognitive_2023; @rohatgi_role_2016], and although PISA does not validate the two-dimensionality as ICILS does in its reports [@fraillon_preparing_2020], there are relevant publications that use the ICILS approach for grouping PISA DSE items [@tomte_genderdifferences_2011; @hristov_understanding_2026]. 

The dimensions of the DSE are not only relevant to contrast for theoretical reasons, but also because consideration of this approach has an impact on the distribution among groups. A series of studies using the two-dimensional ICILS model has shown that girls outperform or equal boys in general DSE, but present lower scores on specialized DSE [@kaarakainen_differences_2017; @cusso-calabuig_effects_2018; @cai_gender_2017]. In turn, the literature consistently reports that students with low expectations of specialized self-efficacy sometimes score lower on standardized tests of digital skills [@aesaert_accuracy_2017; @weigold_measuring_2021; @campos_digital_2024]. 

Considering the previous statements, we propose four hypotheses to be tested on this research:

$H_{1}$: It is possible to identify two latent dimensions of digital self-efficacy (general and specialized) on PISA 2022 and ICILS 2023.

$H_{2}$: The bi-dimensional measurement model of digital self-efficacy is equivalent across countries in ICILS 2023 and PISA 2022.

$H_{3}$: The bi-dimensional measurement model of digital self-efficacy is equivalent between girls and boys.

$H_{4}$: General and Specialized DSE exhibit distinct patterns of association with gender and national context.
