---
editor: visual
---

# Methods

## Data

ICILS 2023 employed a two-stage cluster sampling approach across 34 countries and more than 130,000 studentes around the world. In the first stage, schools with students in the target grade were randomly selected using a probability proportional to size (PPS) method. In the second stage, one intact class was randomly selected within each sampled school, and all students in that class were invited to participate [@fraillon_international_2024].

PISA 2022 target population consists of 15-year-old students attending educational establishments, employing a two-stage stratified sampling design. In the first stage, schools were systematically selected with PPS from national sampling frames. In the second stage, a target number of students (typically 42) were randomly selected with equal probability from within each sampled school [@oecd_pisa_2024]. Official subset of data reach around 393,000 students, nested on 52 countries (maily OECD).

To ensure comparability, both datasets were filtered to include only those countries which participated in PISA ICT questionnaire and the ICILS survey. Furthermore, to maximize the overlap between the samples, specific adjustments were made. In ICILS data, Germany is reported as two separate regions reflecting its distinct educational systems; for this analysis, these regions were aggregated to form a single national entity. Similarly, the ICILS data for Belgium were collected exclusively from the Flemish Community (Flanders) in this wave. To align the datasets, the data from Flanders were treated as representative of the entire country.

The final country-level sample include 22 countries, with 91,132 nested students in ICILS and 183,902 in PISA.

## Variables

Both studies include a module on digital self-efficacy in their questionnaires. In ICILS the 13 items are introduced with the phrase *"How well can you do:"* and recoded categories are 1 = I do not think I could do this; 2 = I have never done this, but I could work out how to do it; 3 = Moderately well; 4 = Very well. PISA prefaces its 14-item module with the question *"To what extent are you able to do the following tasks when using \<digital resources\>?"*, where \<digital resources\> is a placeholder for a term adapted to the target culture. PISA recoded categories are 1 = I cannot do this; 2 = I struggle to do this on my own; 3 = I can do this with a bit of effort; 4 = I can easily do this. Responses as "I don't know" was threated as missing values. A complete comparison of the items from both surveys was presented in [Table @tbl-comparison], highlighting the concordances and distinctions between the studies, and the type of DSE we are assuming to match the item.

We also consider the three-digit ISO country code and the student's sex (recoded as 1 = male and 2 = female) from both datasets.

## Analytical Strategy

All data management and analyses were conducted using the R statistical environment. The data wrangling were developed using R packages `dplyr` and `haven`.

The main analyses were performed within a Confirmatory Factor Analysis (CFA) framework to test the hypothesized two-factor structure of DSE [@brown_confirmatory_2015]. The CFA models were estimated with the `lavaan` package [@rosseel_lavaan_2012]. Given the ordinal nature of the Likert-scale items, they were treated as ordered categorical variables. Therefore, models were estimated using the Weighted Least Squares Mean and Variance Adjusted (WLSMV) estimator. Missing data were handled using pairwise deletion, which is the standard approach for this estimator in lavaan besides the (default) listwise deletion.

In both studies, the complex structure of the samples was addressed using sample weights (Final Student Weights in ICILS and Senate Weights in PISA). This weighting was applied to all models and descriptive analyses to ensure representative parameter estimates. However, due to software limitations, it was not possible to correct standard errors for the complex survey design (via the Jackknife method for ICILS, Fay’s method for PISA, or cluster-robust estimation). At present, the `lavaan` package does not support: 1) the use of robust estimators for categorical variables in conjunction with clustering; 2) the simultaneous use of sampling weights combined with clustering; and 3) the implementation of replicate variance estimation methods. Consequently, standard errors were estimated without explicit correction for the nested design; this approach was selected to prioritize the unbiased estimation of the population structure and item parameters, which required the simultaneous use of sampling weights and the WLSMV estimator.

To evaluate the goodness-of-fit of the models, chi-square (χ²) test was used. However, due to the test's sensitivity to large sample sizes, model evaluation primarily relied on a complementary set of fit indices: the Comparative Fit Index (CFI), the Tucker-Lewis Index (TLI), and the Root Mean Square Error of Approximation (RMSEA). Following common guidelines, CFI and TLI values of .95 or higher are considered indicative of excellent fit, while values between 0.90 and 0.95 are considered acceptable. For RMSEA, values of .06 or less indicate a close fit, while values up to .08 are considered adequate [@brown_confirmatory_2015; @wang_structural_2012]. To verify the reliability of the models, McDonald's $\omega$ will be reported. Values above .7 indicate good reliability [@hair_multivariate_2009]. In terms of convergent validity, statistically significant factor loadings of at least .5 will be required. In addition, an Average Variance Extracted (AVE) of at least .5 will be required, which means that the model explains 50% of the variance of the items on average [@cheung_reporting_2024]. The R `semTools` package was used to perform reliability and convergent validity analyses [@jorgensen_semtools_2025].

First, a pooled model was estimated to test the overall fit of the hypothesized model across both studies. In instances where the initial model failed to achieve an acceptable fit, a principled procedure of model re-specification was undertaken. Sources of model misfit were diagnosed by examining multiple indicators, including residual correlation matrices and modification indices. Items identified as primary sources of misspecification were considered for removal. Any modification was contingent upon a strong theoretical justification on @ulfert-blank_assessing_2022 framework: Items with ambiguity dimension or content overlap were prioritized to remove, ensuring that the construct's content validity was not compromised. This process was performed judiciously to arrive at a final, well-fitting model that remained theoretically coherent. A factor was required to have a minimum of three indicators to be retained.

In the next step, to test the comparability of this measurement model across countries and genders, a series of Multi-Group Confirmatory Factor Analyses (MGCFA) was conducted to assess Measurement Equivalence or Invariance (ME/I) [e.g., @beaujean_latent_2014; @davidov_measurement_2014]. This procedure involves testing three sequential levels of invariance by imposing progressive restrictions: **1) configural invariance**, which tests if the same factor structure holds for all groups; **2) metric invariance**, which adds the constraint that factor loadings are equal across groups; and **3) scalar invariance**, which further constrains item intercepts (or thresholds for ordinal items) to be equal [@cheung_evaluating_2002; @milfont_testing_2010]. The establishment of invariance between these nested models was evaluated by examining the change in CFI (ΔCFI) and RMSEA (ΔRMSEA). Specifically, for **metric (weak) invariance**, a change in CFI of ≥ -.004 and a change in RMSEA of ≤ .05 were considered acceptable. For **scalar (strong) invariance**, a ΔCFI of ≥ -.004 and a ΔRMSEA of ≤ .01 were considered adequate [@rutkowski_measurement_2017]. Achieving metric invariance is a prerequisite for further analysis of association among dimensions of DSE with factors. Achieving scalar invariance is a prerequisite for further analysis of association among dimensions of DSE with factors and estimation of the latent means across countries and across gender.

Upon establishing scalar invariance, latent mean scores of General and Specialized DSE country distribution are explored. In the next step the magnitude of the DSE gender gap is visualized for each country.