---
title: "deleted_info"
format: html
---

# Dimensions of Self-efficacy

In the literature, there is broad agreement on the minimal definitions of self-efficacy proposed initially by @bandura_selfefficacy_1982; however, two approaches emerge that emphasize specific elements of the construct. The first perspective focus on task self-efficacy, understood as the perceived capabilities required to achieve a certain level of performance when mastering an activity. The second is oriented toward regulatory self-efficacy, which is more concerned with how confidence supports resilience in the face of potential barriers around the social context of individuals. While capability-focused studies emphasize the degree of difficulty of the task and the linear progression toward mastery, more attitudinal approaches highlight persistence and resistance when confronting the adversities present in the environment where the activity takes place [@marlatt_selfefficacy_1995; @schwarzer_socialcognitive_2000; @williams_confounded_2016].

Studies examining self-efficacy with technologies tend to focus more on students’ ability to perform increasingly advanced technological tasks than on their capacity to recover from situations that may undermine their confidence. The underlying assumption in this line of research is that competence develops through progressively more complex levels of technological knowledge—from simple skills such as opening a file to more demanding tasks such as programming or web development. However, these measurement batteries typically assess, in the abstract, whether students believe they can perform a task, without situating the technology within a specific social context in which the skill must actually be applied. Consequently, self-efficacy instruments in the technological domain often structure their dimensionality around the degree of task complexity, rather than around competence areas or types of use to which the tasks belong [@bandura_selfefficacy_1995; @fabia_students_2024; @mekheimer_technological_2025].

Although some studies define DSE as a simple unidimensional construct, measuring individuals’ task achievement in using digital technologies without distinguishing levels of complexity [@hatlevik_digital_2015; @rohatgi_role_2016], a large range of studies adopt a bidimensional approach. Within this frame, a first level of achievement is categorise as *general or basic DSE*, which considers widespread skills around handling information, communicating or collaborating through technologies and creating digital content. A second level of achievement, jerarquically above the previous one, adresses high technical expertise on computational tasks such as using programming languages, application development, or website management, generally labelled as *specialized or advanced DSE* [@pasha_crossnational_2024; @gebhardt_gender_2019].

Both the unidimensional and the bidimensional approaches not only influence measurement instruments but also lead to different research findings: unidimensional models could underestimate the predictive power of DSE for complex digital enviroments, while bidimensional models offer greater explanatory precision but can introduce challenges such as construct overlap or reduced generalizability across contexts, limiting findings across educational systems and cultural contexts [@aesaert_accuracy_2017; @siddiq_there_2019; @scherer_gender_2023; @campos_digital_2023]. Thus, the choice between unidimensional and bidimensional models of DSE is not merely theoretical, as it has significant implications for the validity, reliability, and utility of research on digital competence development, especially in the case of large-scale studies, which require consistent data at a cross-cultural level.

# ILSA and DSE

International Large-scale Assessment have become one of the most important types of studies in the field of education, characterized by the deployment of their surveys throughout the educational systems of the world, enabling cross-country analysis with large volumes of data.

There are two main studies that include digital topics in their surveys. First, International Computer and Information Literacy Study (ICILS), belonging to the International Evaluation Assosiation (IEA), and second, the Programme for International Student Assessment (PISA), which is developed by the OECD. The main objective of ICILS is to measure the Computer and Information Literacy (CIL) of students through a standardized test, and predict the behavior of the score by variables of social background obtained from different questionnaires. PISA is recognized by measuring the knowledge in reading, mathematics and science of 15-year-old adolescents, evaluating how prepared they are to use this topics on the real life. This study stands out for the great thematic versatility of its questionnaires, including digital themes in the ICT familiarity module.

As can be viewed on @tbl-comparison, these studies understands and measures DSE differently. ICILS proposes a two-dimensional perspective of DSE, distinguishing between general and specialized DSE. The general dimension encompasses tasks that do not require in-depth knowledge of how digital devices work like search and find information on internet. Specialized DSE tasks requires greater mastery of digital skills, as they are more complex to perform, like create a computer program. In contrast, PISA has a one-dimensional approach that can be inferred from its framework [@oecd_pisa_2023], but the items it considered also goes from simple skills, as text editing in digital services, to more complex ones like identifying the source of an error in a software.

```{r}
#| label: tbl-comparison
#| tbl-cap: "DSE item comparison between PISA and ICILS."

library(kableExtra)
library(openxlsx)

table <- openxlsx::read.xlsx(here::here("input", "documents", "batteries_icils_pisa_selfeff_comparison.xlsx"), fillMergedCells = TRUE)
table[is.na(table)] <- ""

table |>
  dplyr::select(Competence.area,Competence,Common.label,Type.of.DSE,ICILS.Label,PISA.Label)|>
  knitr::kable() |>
scroll_box(height="800px")

#Hay que añadir la cantidad de NA por item en esta tabla
```

The different considerations of DSE number of dimensions can be adressed on the distinct approaches both studies have towards self-efficacy concept. ICILS items reflect greater relevance in the completion of a specific task rather than in carrying out an evaluative process of how to solve a situated problem. PISA presents greater definitions on the existence of a scenario where the tasks are involved, and a procedural for overcoming them. In this sense, ICILS places greater emphasis on task self-efficacy than PISA, and therefore, PISA do not attempt to differentiate tasks based on their level of technical difficulty, but on the the greatest diversity of elements that contextualize the type of task.

A careful analysis of both batteries reveals that there are differences not only in the number of dimensions, but also in the type of skills being considered (see @tbl-comparison). ICILS contains tasks related to information, communication, and digital creation. Among the last one, there are three that are specialized: web development, use of programming languages, and visual coding. PISA, on the other hand, presents two items of advanced digital creation (programming and web development), but also adds a series of other items that refer to the fourth and fifth dimensions of the Digcomp framework, namely safety and problem solving [@europeancommissionjointresearchcentre_digcomp_2022]. The inclusion of these two areas in PISA shows that the dimensionality of the construct was designed focusing more on the type of context of the tasks than on their level of difficulty, as is the case in ICILS.

The more comprehensive scope of the concept of DSE in PISA does not translate into the creation of sub-constructs as in ICILS, but rather the study chooses to reduce its dimensions to just one. Furthermore, it disregards the factor validation rule, as it has a dimension (safety) that has only one item [@kline_principles_2016; @devellis_scale_2022]. And with its DigComp framework approach, tasks such as web development or programming are placed in the same dimension as simple tasks such as writing text or inserting images, even though the literature in the field reports that these tasks are asymmetrically, and even oppositely, related to other variables [@fraillon_preparing_2020; @aesaert_accuracy_2017].

Given the weaknesses of both studies, it is worth asking whether it is possible to establish some degree of comparability between them, so that the results become more robust thanks to the consistency that can be found between two such large-scale samples. ICILS has published reports that reveal the process of construction of its scales [@fraillon_iea_2025], whereas PISA's construct remains opaque in terms of its metrics [@oecd_pisa_2023]. Furthermore, we propose that the logic of ICILS can be extrapolated to the information contained in the PISA battery, but not vice versa. Although by forcing ICILS framework in PISA, it would also be possible to understand the performance of new tasks that ICILS' bi-dimensionality approach don't contemplate, such as pair collaboration, identifying errors or representing logical solutions.