---
format:
  html: 
    toc: true
    keep-tex: true
editor: visual
smooth-scroll: true
number-sections: true
bibliography: "picils.bib"
csl: "apa.csl"
link-citations: true
mainfont: Times New Roman
execute: 
  echo: false
  warning: false
comments:
  hypothesis: true
---

# Measuring Digital Self-Efficacy in International Large-Scale Assessments: A bi-dimensional comparative scale Between ICILS and PISA {.unnumbered}

Daniel Miranda[^1], Ismael Aguayo[^2], Nicolás Tobar[^3], Tomás Urzúa[^4] and Juan Carlos Castillo[^5]

[^1]: Psychology Department, University of Chile. Associate researcher at Center of Social Cohesion and Conflict studies (COES). Adjunct researcher on NUDOS. [damiran1\@uc.cl](mailto:danmiranda@uchile.cl).

[^2]: Research Assistant on NUDOS. Bsc (c) Sociology, Sociology Department, University of Chile. [ismael.aguayo\@ug.uchile.cl](mailto:ismael.aguayo@ug.uchile.cl)

[^3]: Research Assistant on NUDOS. Msc (c) Political Science, Faculty of Government, University of Chile. [nicolas.tobar\@ug.uchile.cl.](mailto:nicolas.tobar@ug.uchile.cl)

[^4]: Research Assistant on NUDOS. Msc (c) Social Sciences, Sociology Department, University of Chile. [tomas.urzua\@ug.uchile.cl](mailto:tomas.urzua@ug.uchile.cl)

[^5]: Sociology Department, University of Chile. Principal researcher on Millennium Nucleus on Digital Inequalities and Opportunities (NUDOS) and at the Center of Social Cohesion and Conflict studies (COES). [juancastillov\@uchile.cl](mailto:juancastillov@uchile.cl) - [jc-castillo.com](jc-castillo.com)

```{r setup}

# Sesion setting

options(scipen=999) #No scientific notation
options(digits = 2) #Round results two decimals


#install.packages("pacman")
library(pacman)

pacman::p_load(
  dplyr, haven, sjlabelled,  psych,  purrr,  tidyr,  sjPlot,  ggplot2, 
  parameters,  table1,  car,  beeswarm,  lme4, scales, ggrepel, corrplot,
  ggtext, patchwork, lavaan, semTools, DT, knitr, kableExtra)

options(scipen = 999)
rm(list = ls()) 

icils <- readRDS(here::here("input", "data", "proc_data", "icils_comparable.rds"))
pisa <- readRDS(here::here("input", "data", "proc_data", "pisa_comparable.rds"))
```

**Abstract**

Understanding students’ beliefs about their capabilities with digital technologies, commonly referred to as digital self-efficacy (DSE), is critical for interpreting cross-national assessments of digital competence. International large-scale assessments differ in how DSE is modeled. The International Computer and Information Literacy Study (ICILS) adopts a bidimensional approach, while the Programme for International Student Assessment (PISA) treats DSE as a unidimensional construct, despite relying on highly similar digital tasks. This study examines whether a bidimensional structure of DSE can be empirically supported in both assessments when analyzed within a comparable cross-national framework. Using confirmatory factor analysis and multi-group measurement invariance testing across countries and gender, we assess the validity and comparability of general and specialized dimensions of DSE. The comparable measure distribution shows, consistently across countries, smaller gender differences on general DSE, while specialized DSE systematically favors boys. The results support a two-factor structure in both datasets and show relatively acceptable levels of measurement equivalence across national contexts and between girls and boys. Achieving adequate model fit required the removal of several items, highlighting the possible obsolescence of the batteries in a rapidly changing digital environments. These findings refine the interpretation of DSE in international assessments and emphasize the importance of construct dimensionality and updating the instruments measures by new technological innovations.

{{< include 1-intro.qmd >}}

{{< include 2-dse.qmd >}}

{{< include 3-methods.qmd >}}

{{< include 4-results.qmd >}}

{{< include 5-discussion.qmd >}}

{{< include 6-appendix.qmd >}}